/c16/lslidar_driver_node:
  ros__parameters:
    packet_rate: 840.0
    device_ip: 192.168.1.200
    msop_port: 2368
    difop_port: 2369
    pcl_type: false
    lidar_type: c16
    add_multicast: false
    group_ip: 224.1.1.2
    use_gps_ts: false
    min_range: 0.3
    max_range: 200.0
    frame_id: lslidar
    distance_unit: 0.4
    angle_disable_min: 0
    angle_disable_max: 0
    angle_disable_bands_min: [0, 310]
    angle_disable_bands_max: [50, 360]
    horizontal_angle_resolution: 0.18
    scan_num: 0
    read_once: false
    publish_scan: true
    topic_name: lslidar_point_cloud
    coordinate_opt: false
    #pcap: /home/ls/work/fuhong/data/V4.0/c16.pcap
