<?xml version="1.0"?>

<robot name="scout_mini"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="M_PI" value="3.141592653" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini.xacro" />

    <xacro:include filename="$(find rigel_description)/urdf/slam_sys.urdf.xacro"/>
    <xacro:ice9_slam parent="base_link" name="slamsys">
        <origin xyz="0 0.161438 ${0.335382 + wheel_radius}" rpy="0 0 0" />
    </xacro:ice9_slam>

</robot>